"""Garmin -> Google Drive sync, run from Streamlit Community Cloud instead
of the Claude Code cloud sandbox.

Why this file exists: garminconnect's anti-bot-evasion login strategies
rely on spoofing a browser TLS fingerprint, which doesn't survive the
sandbox's TLS-terminating proxy, and the sandbox's shared egress IP is
already rate-limited by Garmin. Streamlit Cloud gives the same Python
code a different network path plus a real interactive form for the 2FA
code (no file-polling hack needed here - Streamlit keeps the in-progress
Garmin client alive in st.session_state between reruns).

Required secrets (Settings -> Secrets in the Streamlit Cloud dashboard) -
only two values, and you read both yourself from Google Cloud Console
(APIs & Services -> Google Auth Platform -> Clients -> your TV/limited-
input client), nothing to copy from anywhere else:

    [google]
    client_id = "..."
    client_secret = "..."

Everything else (the Google refresh token, the key used to encrypt the
Garmin session token) is generated by this app itself on first use and
held only in memory for the running app's lifetime - if the app fully
restarts, you redo the short one-tap Google reconnect and, if needed, the
Garmin login below; nothing sensitive needs to be typed into secrets.toml
or relayed through anywhere else.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "src"))

import requests
import streamlit as st
from cryptography.fernet import Fernet
from garminconnect import Garmin

from drive_writer import read_file, write_file
from gdrive_auth import DEVICE_CODE_URL, SCOPE, TOKEN_URL, ensure_garmin_folder, refresh_access_token
from sync import run_sync_with_client

GARMIN_TOKEN_FILENAME = "garmin-session-token.enc"

st.set_page_config(page_title="Garmin AI Sync", page_icon="🏃")
st.title("Garmin AI Sync")


class _AppState:
    """Shared, in-memory, process-lifetime state - one instance for the
    whole running app (not per viewer), which is fine for a single-user
    tool. Nothing here is written to disk.
    """

    def __init__(self) -> None:
        self.google_refresh_token: str | None = None
        self.garmin_encryption_key: bytes = Fernet.generate_key()


@st.cache_resource(show_spinner=False)
def _app_state() -> _AppState:
    return _AppState()


def _start_google_device_flow(client_id: str) -> dict:
    resp = requests.post(DEVICE_CODE_URL, data={"client_id": client_id, "scope": SCOPE}, timeout=30)
    resp.raise_for_status()
    return resp.json()


def _poll_google_device_flow(client_id: str, client_secret: str, device_code: str) -> str | None:
    """Returns the refresh token once granted, or None while still pending."""
    resp = requests.post(
        TOKEN_URL,
        data={
            "client_id": client_id,
            "client_secret": client_secret,
            "device_code": device_code,
            "grant_type": "urn:ietf:params:oauth:grant-type:device_code",
        },
        timeout=30,
    )
    body = resp.json()
    if resp.status_code == 200:
        return body["refresh_token"]
    if body.get("error") in ("authorization_pending", "slow_down"):
        return None
    raise RuntimeError(body.get("error", "unknown_error"))


def _google_connect_flow(state: _AppState) -> None:
    st.subheader("Mit Google Drive verbinden")
    g = st.secrets["google"]

    if "device_flow" not in st.session_state:
        if st.button("Verbindung starten"):
            st.session_state["device_flow"] = _start_google_device_flow(g["client_id"])
            st.rerun()
        return

    flow = st.session_state["device_flow"]
    st.write(f"1. Öffne: {flow['verification_url']}")
    st.write(f"2. Gib diesen Code ein: **{flow['user_code']}**")
    if st.button("Ich habe bestätigt"):
        try:
            token = _poll_google_device_flow(g["client_id"], g["client_secret"], flow["device_code"])
        except RuntimeError as e:
            st.error(f"Fehler: {e}")
        else:
            if token is None:
                st.warning("Noch nicht bestätigt - kurz warten, dann nochmal klicken.")
            else:
                state.google_refresh_token = token
                del st.session_state["device_flow"]
                st.rerun()


def _fernet(state: _AppState) -> Fernet:
    return Fernet(state.garmin_encryption_key)


def _load_stored_garmin_tokenstore(state: _AppState, access_token: str, folder_id: str) -> str | None:
    raw = read_file(access_token, folder_id, GARMIN_TOKEN_FILENAME)
    if raw is None:
        return None
    try:
        return _fernet(state).decrypt(raw).decode("utf-8")
    except Exception:
        # Encrypted with a key from a previous app instance (e.g. after a
        # restart) - the key lives only in memory, so this is unrecoverable;
        # fall through to a fresh Garmin login instead of crashing.
        return None


def _store_garmin_tokenstore(state: _AppState, access_token: str, folder_id: str, tokenstore: str) -> None:
    encrypted = _fernet(state).encrypt(tokenstore.encode("utf-8"))
    write_file(access_token, folder_id, GARMIN_TOKEN_FILENAME, encrypted.decode("ascii"), "application/octet-stream")


def _get_garmin_client(state: _AppState, access_token: str, folder_id: str) -> Garmin | None:
    tokenstore = _load_stored_garmin_tokenstore(state, access_token, folder_id)
    if tokenstore is None:
        return None
    garmin = Garmin()
    try:
        garmin.login(tokenstore=tokenstore)
    except Exception:
        return None
    _store_garmin_tokenstore(state, access_token, folder_id, garmin.client.dumps())
    return garmin


def _garmin_login_flow(state: _AppState, access_token: str, folder_id: str) -> None:
    st.subheader("Einmaliger Garmin-Login")

    if "mfa_pending_garmin" not in st.session_state:
        with st.form("garmin_credentials"):
            email = st.text_input("Garmin-E-Mail")
            password = st.text_input("Garmin-Passwort", type="password")
            submitted = st.form_submit_button("Anmelden")
        if submitted:
            garmin = Garmin(email=email, password=password, return_on_mfa=True)
            try:
                status, _ = garmin.login()
            except Exception as e:
                st.error(f"Login fehlgeschlagen: {e}")
            else:
                if status == "needs_mfa":
                    st.session_state["mfa_pending_garmin"] = garmin
                    st.rerun()
                else:
                    _store_garmin_tokenstore(state, access_token, folder_id, garmin.client.dumps())
                    st.success("Login erfolgreich, Token gespeichert.")
                    st.rerun()
    else:
        st.info("Garmin hat dir einen 2FA-Code geschickt (E-Mail oder App).")
        with st.form("garmin_mfa"):
            code = st.text_input("2FA-Code")
            confirmed = st.form_submit_button("Bestätigen")
        if confirmed:
            garmin = st.session_state["mfa_pending_garmin"]
            try:
                garmin.resume_login(None, code)
            except Exception as e:
                st.error(f"2FA fehlgeschlagen: {e}")
            else:
                _store_garmin_tokenstore(state, access_token, folder_id, garmin.client.dumps())
                del st.session_state["mfa_pending_garmin"]
                st.success("Login erfolgreich, Token gespeichert.")
                st.rerun()


state = _app_state()

if state.google_refresh_token is None:
    _google_connect_flow(state)
    st.stop()

access_token = refresh_access_token(
    st.secrets["google"]["client_id"], st.secrets["google"]["client_secret"], state.google_refresh_token
)
folder_id = ensure_garmin_folder(access_token)
st.caption(f"Google Drive verbunden - Ordner-ID: {folder_id}")

garmin = _get_garmin_client(state, access_token, folder_id)

if garmin is None:
    _garmin_login_flow(state, access_token, folder_id)
else:
    st.success("Mit gespeichertem Garmin-Token angemeldet.")
    days = st.number_input("Anzahl Tage", min_value=1, max_value=60, value=3)
    dry_run = st.checkbox("Nur testen, nichts nach Drive schreiben", value=False)
    if st.button("Sync jetzt ausführen"):
        with st.spinner("Synchronisiere..."):
            result = run_sync_with_client(garmin, access_token, folder_id, int(days), dry_run)
        days_with_data = sum(
            1 for d in result["days"]
            if any(d.get(k) is not None for k in (
                "sleep", "hrv", "resting_hr", "body_battery", "stress", "steps", "training_readiness"
            ))
        )
        st.success(
            f"Fertig. {days_with_data}/{len(result['days'])} Tage mit Werten, "
            f"{len(result['activities'])} Aktivitäten."
        )
        st.json(result)
